### ISSUE TITLE
Error happens while building 

### ISSUE THREAD

**Issue by Maples7** [CandyGumdrop/proj#3]
while doing `mix compile`:

```
==> proj
cc -fPIC -Isrc -std=c99 -pedantic -Wall -Wextra -Wno-unused-parameter -c src/proj_nif.c -o src/proj_nif.o -I/usr/local/Cellar/erlang/21.3.5/lib/erlang/erts-10.3.4/include
In file included from src/proj_nif.c:3:
/usr/local/include/proj_api.h:37:2: error: 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
#error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
 ^
1 error generated.
make[1]: *** [src/proj_nif.o] Error 1
could not compile dependency :proj, "mix compile" failed. You can recompile this dependency with "mix deps.compile proj", update it with "mix deps.update proj" or clean it with "mix deps.clean proj"
** (MatchError) no match of right hand side value: 2
    /PROJECT_NAME/deps/proj/mix.exs:3: Mix.Tasks.Compile.Proj.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:73: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:53: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:24: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:40: Mix.Tasks.Compile.All.with_logger_app/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.ex:96: Mix.Tasks.Compile.run/1
make: *** [build] Error 1
```

macOS 10.15.1
gcc:
```
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
```
proj: Rel. 6.2.0, September 1st, 2019

**Comment by CandyGumdrop** [comment]
This library unfortunately does not currently support PROJ 5 or PROJ 6 and only supports PROJ.4 4.9.X.  If you'd like to make use of this library in the meantime, you will have to install PROJ.4 4.9.3.

This may run in PROJ 5, or in PROJ 6 with `-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H`, however I believe something has changed in regards to thread safety where it may not be safe to use this library as is with those versions of PROJ.

**Comment by CandyGumdrop** [comment]
I've released a new version of Proj which builds with libproj >= 5.
